### ISSUE TITLE
Make Home Page Front-end more organised

### ISSUE THREAD

**Issue by shimonaverma** [shimonaverma/Social-Network#1]
Use html and css to make frontend better.

**Comment by hima-Megahed** [comment]
hello @shimonaverma I will help ASAP 👍

**Comment by yati1998** [comment]
I would also like to contribute to it

**Comment by hima-Megahed** [comment]
@shimonaverma  I'm having some troubles in running the application, there are a lot of errors I fixed some of them but when I sign up and go to "app/" it gives me a bad request.

**Comment by shimonaverma** [comment]
I will look into the issue

**Comment by hima-Megahed** [comment]
I fixed Some of them please check'em out.

**Comment by SinghSatbir** [comment]
Hey, I want to work on this issue. Please assign it to me.
